package config

import "vendor:raylib"


ASTEROID_RADIUS: f32 : 42
ASTEROID_COLOR :: raylib.WHITE

ASTEROID_X: f32 : 0 + ASTEROID_RADIUS
ASTEROID_Y: f32 : 0 - ASTEROID_RADIUS

ASTEROID_SPEED: f32 : 415