package config

import "vendor:raylib"


WINDOW_WIDTH :: 800
WINDOW_HEIGHT :: 600
WINDOW_CENTER_X: f32 : WINDOW_WIDTH / 2
WINDOW_CENTER_Y: f32 : WINDOW_HEIGHT / 2 
WINDOW_TITLE :: "Asteroids"
WINDOW_BG_COLOR :: raylib.BLACK

BORDER_LEFT :: 0
BORDER_RIGHT :: WINDOW_WIDTH
BORDER_TOP :: 0
BORDER_BOTTOM :: WINDOW_HEIGHT
